### PR TITLE
Fix for #213

### PR DESCRIPTION
**Pull request by ekes**

### CODE REVIEW

**Comment by ekes** [comment]
If someone can double check this. I just realized I'm not 100% sure that module exists is returning the correct value when it has just been enabled in the previous update, my db might not have been clean by that point.

**Review by andybroomfield — APPROVED** [review]
This resolves the issue for me.

**Comment by ekes** [comment]
Same update as [search](https://github.com/localgovdrupal/localgov_search/pull/43#issuecomment-1195620755) to make sure it's good if your ran 8007 and 8008 in one go, as well as separately.

**Comment by andybroomfield** [comment]
See https://github.com/localgovdrupal/localgov_search/pull/43#issuecomment-1196369312

**Pull request merged**
