### PR TITLE
Changed config for directory channel teaser

### LINKED ISSUE #59: Fix Teaser view mode of the Directory channel content type
The Directory channel content type's **Teaser** view mode is currently no different from its **Default** view mode.  The Teaser view mode should only display the body summary or trimmed body content similar to the Directory entry content types (e.g. localgov_directories_page)

FAO @finnlewis @willguv

### PR DESCRIPTION
**Pull request by mattrfletcher**
Fix for Fix Teaser view mode of the Directory channel content type:https://github.com/localgovdrupal/localgov_directories/issues/59

### CODE REVIEW

**Comment by mattrfletcher** [comment]
@finnlewis @stephen-cox @ekes @Adnan-cds

As mentioned at the meeting this is a pull request that needs to be approved.

**Comment by stephen-cox** [comment]
@mattrfletcher Please merge the 2.x branch into this work and push to trigger the tests again. Once you've done that please add me as a reviewer and I'll take a look

**Comment by mattrfletcher** [comment]
> @mattrfletcher Please merge the 2.x branch into this work and push to trigger the tests again. Once you've done that please add me as a reviewer and I'll take a look

@stephen-cox I've done the above. Not sure how to add you as a reviewer or if i actually can.

**Comment by stephen-cox** [comment]
@mattrfletcher Do you see a 'Reviewers' section in the right-hand sidebar? If so, you should be able to add be there. If you don't see it I'll have a look to see if there are some permissions I can set to give you access

**Comment by mattrfletcher** [comment]
> @mattrfletcher Do you see a 'Reviewers' section in the right-hand sidebar? If so, you should be able to add be there. If you don't see it I'll have a look to see if there are some permissions I can set to give you access

I did see that before but didn't see a way to add someone. The only thing I can do currently is click on the convert to draft link.

**Comment by mattrfletcher** [comment]
@stephen-cox Could you or someone else approve the test workflow. If it passes all tests is there anything more to do before this can be merged.

**Comment by mattrfletcher** [comment]
@stephen-cox Now that all tests have passed could this now be merged.

**Comment by stephen-cox** [comment]
Looks good. Thanks @mattrfletcher. Merging

**Pull request merged**
