### PR TITLE
Proximity search

### LINKED ISSUE #189: Proximity searching in SQL backend of Search API
@Adnan-cds has been looking at this at Croydon.

Trying to add the location proxiimity search to SearchAPI database backend to allows us to filter by proximity to a location.

See https://lbc-app-w-localgov-corpwebsite-dev5.azurewebsites.net/parking-streets-and-transport/parking/places-park/find-council-car-parks-croydon?search_api_fulltext=&latlon%5Bpostcode%5D=cr0+1ea&latlon%5Bsearch_radius%5D=805 
image

We also saw this issue: https://www.drupal.org/project/search_api/issues/2877319

Let us know how you get on @Adnan-cds

### PR DESCRIPTION
**Pull request by Adnan-cds**
Adding support for proximity search to the out-of-the-box Directory search View.

## Change summary
- Adds a new field called *Proximity search settings* to the Directory channel content type.  On a fresh installation of Drupal that has localgov_directories enabled, this addition happens when the localgov_location field is added to a Directory entry content type.  On the other hand the update hook takes care of this on existing sites with existing location-based Directory entries.
- At the same time, a new Views display is added to the existing localgov_directory_channel View.  This display offers proximity search.  A corresponding facet that uses this Views display as data source is also made available.  This makes facets available on proximity search pages.
- Majority of the code changes in this pull request deals with the above mentioned configuration changes.

### Site setup
- `composer require localgovdrupal/localgov_directories:'dev-feature/2.x/189-proximity-search as 2.x-dev' --with-all-dependencies`
- drush updatedb
### Search process
- Login and edit a Directory channel that lists location-based directory entries such as localgov_directories_venue.
- Enable the *Proximity search settings* checkbox and save.
- The Directory search block should now include a location search filter.  This filter takes an address (postcode works just fine) and a search radius.  The OpenStreetMap geocoder that comes bundled with the localgov_directories module is used by default.  Other geocoders work too; these can be configured from the localgov_directory_channel View's *Proximity search* display's *Proximity* filter.

## Patches
Depends on a few external patches:
1. [search_api patch](https://www.drupal.org/project/search_api/issues/2877319) for MySQL-only location search.
2. [search_api_location](https://www.drupal.org/node/3283994) patch for bug fix.
3. [search_api_location](https://www.drupal.org/node/3296407) patch for schema error.

The first one adds MySQL-only location search support to search_api.  Location-based search is already supported by the search_api_solr module.  So if you are using Solr, you don't need patch no. 1.

We don't know if patch no. 1 will be eventually accepted or not.  We should wait on this pull request for that reason only.  But let that not stop you from reviewing the code :)

Resolves #189

### CODE REVIEW

**Comment by finnlewis** [comment]
@Adnan-cds has been working on this and we're discussing in the Merge Monday meeting.

We have recently separated out the search backends to support either db or solr ( and others).

Outstanding questions / work: 

 - Add checks to see if we have a search backend and if so if the backend supports the proximity search, then re-import config.

**Comment by Adnan-cds** [comment]
Ready for testing.

I have dropped [the patch](https://www.drupal.org/project/search_api/issues/2877319) that adds location search support to Search API's MySQL search backend.  So you will need Solr to test this.

But if you are keen on trying this with MySQL, then try:
```
$ cd /path/to/search_api
$ curl https://www.drupal.org/files/issues/2022-11-23/2877319-41-db_backend_location_support.patch | patch -p1
```

Good (or bad) to know: MySQL does its distance calculation in meters.  Solr *by default* uses [Kilometers](https://solr.apache.org/guide/6_6/spatial-search.html#SpatialSearch-SearchingwithQueryParsers) and that too in round figures (2km is fine, 2.7km is treated as 2km).  This is complicating things.  ~As a result, if you use MySQL for testing this change, the distance shown alongside each directory entry in the search result will be incorrect.~  However, proximity search should work okay for both MySQL and Solr.

Also, this change is using two patches for the search_api_location module.  If you can test these patches, and provide some feedback in the d.o issue queue, that would help a lot:
- https://www.drupal.org/node/3283994
- https://www.drupal.org/node/3296407

**Comment by finnlewis** [comment]
It works!!! 

I tested with the demo content

Enable localgov_demo
Enable LocalGov Search Solr
Edit the "Directories" search index and change server to the "Sitewide search (solr)"
Edited "LocalGov Drupal Collaborators" directory channel, enabled "Proximity search settings" and saved.
Re-indexed the "Directories" search index 
Hit /localgov-drupal-collaborators
I can now search for entries less than 5 miles from London

image

Or less than 5 miles from OX4 1EL

image

**Comment by finnlewis** [comment]
I love it @Adnan-cds - sorry it has taken so long to test! 

There are a fair few changes in the code, but it all seems to work for me. 

@ekes @andybroomfield @stephen-cox anyone else fancy reviewing the code changes before approving this?

**Comment by finnlewis** [comment]
Just tested with the database too... and that works just as well.

I applied the patch from https://www.drupal.org/node/2877319 - then noticed that it has also been merged! Nice work @Adnan-cds !

**Comment by finnlewis** [comment]
So, once there is a new release of search_api - this should work with database and solr backends, right @Adnan-cds ?

**Comment by Adnan-cds** [comment]
> So, once there is a new release of search_api - this should work with database and solr backends, right @Adnan-cds ?

Right :)

**Comment by finnlewis** [comment]
@andybroomfield we're just talking about this on Merge Monday, and @Adnan-cds is interested in you trying this with your existing data to see how it plays.

**Comment by finnlewis** [comment]
From discussion in Merge Monday: 
 - @ekes @stephen-cox @finnlewis will do code reviews
 - we want to wait for a release search_api (for the database search) and search_api_location (to fix the php warning in watchdog log)
 - write some documentation to explain how this will work on existing sites

**Review by ekes — APPROVED** [review]
:+1: 

Might be good to get a couple of people to try installing this into their existing sites, but from my testing so far, and the automated test, seems fine there.

Deploys new just fine. We'll want to update the default demo content probably.

Run through the code. Nicely clarifies some bits. Nothing stood out to do further.

I did stumble on one thing for the documentation:- ST_DISTANCE_SPHERE that's used by the facet is more recently in mariadb than mysql. The patch version that lando installs for 10.3 - 10.5 doesn't include it. In which case it just fails with a visible error message "A database exception occurred while searching."

**Comment by ekes** [comment]
> we want to wait for a release search_api and search_api_location

Is the search_api_location out already. Search API might take longer however. If by the time we get some people to test and document installing on their existing sites it's still not out - I'm assuming that might take a bit - after that we should probably try and encourge an new release :)

**Comment by finnlewis** [comment]
Discussing in Merge Monday meeting, @andybroomfield could you test this on your site to double check it doesn't cause any major issues?

**Comment by ekes** [comment]
https://mariadb.com/kb/en/st_distance_sphere/

ST_DISTANCE_SPHERE was introduced in [MariaDB 10.2.38](https://mariadb.com/kb/en/mariadb-10238-release-notes/), [MariaDB 10.3.29](https://mariadb.com/kb/en/mariadb-10329-release-notes/), [MariaDB 10.4.19](https://mariadb.com/kb/en/mariadb-10419-release-notes/) and [MariaDB 10.5.10](https://mariadb.com/kb/en/mariadb-10510-release-notes/).

**Comment by Adnan-cds** [comment]
Do you think the following description going into the [Proximity search](https://github.com/localgovdrupal/localgov_directories/blob/feature/2.x/189-proximity-search/README.md#proximity-search) section of the README would clarify the MariaDB requirements?:

```
### Supported database backends
The [dev release of the search_api module](https://www.drupal.org/project/search_api/releases/8.x-1.x-dev) now supports location-based search.  Supported database versions are:
- MySQL 5.7 and later.
- MariaDB 10.2.38, 10.3.29, 10.4.19, 10.5.10 and later.
```

**Comment by ekes** [comment]
> Do you think the following description going into the [Proximity search](https://github.com/localgovdrupal/localgov_directories/blob/feature/2.x/189-proximity-search/README.md#proximity-search) section of the README would clarify the MariaDB requirements?:
> 
> ```
> ### Supported database backends
> The [dev release of the search_api module](https://www.drupal.org/project/search_api/releases/8.x-1.x-dev) now supports location-based search.  Supported database versions are:
> - MySQL 5.7 and later.
> - MariaDB 10.2.38, 10.3.29, 10.4.19, 10.5.10 and later.
> ```

Sounds good to me.

**Comment by Adnan-cds** [comment]
I have [added](https://github.com/localgovdrupal/localgov_directories/blob/feature/2.x/189-proximity-search/README.md#supported-database-backends) the minimum database requirements in the README.  Finn, please let me know if I should merge this now or wait for the next search_api module release.

**Comment by finnlewis** [comment]
@ekes and @Adnan-cds discussing whether to release this now or wait for search_api to make a release. 

Decided to wait until the end of March and perhaps release then with suitable release notes.

**Comment by ekes** [comment]
[8.x-1.29](https://www.drupal.org/project/search_api/releases/8.x-1.29) Stable release covered by the Drupal Security Team released 27 March 2023

**Comment by ekes** [comment]
This is merged and squashed as 0325940

**Comment by finnlewis** [comment]
This was actually merged, but Github was having a wobble when we merged and released it.

Closing.

**Pull request closed without merging**
