### PR TITLE
Use once for adding return to results link. Fixes #100 rework.

### LINKED ISSUE #100: "Back to search results" link [now repeats?]
The original Croydon design for directories included a "back to search" results link above the search box

directory-entry-top

This is shown if a user has reached this page from a directory channel. The link takes them back to the channel with the same facets applied as when they left it

If the user arrived by other means (eg via a Google search) the "back to search results" link is not shown

### PR DESCRIPTION
**Pull request by ekes**

### CODE REVIEW

**Comment by ekes** [comment]
Am I allowed to use '.?' https://caniuse.com/mdn-javascript_operators_optional_chaining

If it breaks it'll just not show the link (and have a js error) I'd assume.

**Review by Adnan-cds — APPROVED** [review]
Hi Ekes,
Code looks okay and works okay.  I just want to point out that the browser support for the **optional chaining operator** is slightly over a [year old](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility).  If you feel comfortable about it then feel free to merge it.  I don't know really what to do about these type of issues.

I tried to find out what Babel with Drupal core's settings has to say about it and the following code was churned out for ```once('directory-return-link', searchForm).shift()?.insertBefore(returnLink, searchForm.firstChild);```:

```(_once$shift = once('directory-return-link', searchForm).shift()) === null || _once$shift === void 0 ? void 0 : _once$shift.insertBefore(returnLink, searchForm.firstChild);```

Here's the reproduction steps:
```
$ cd /path/to/drupal/core
$ pushd misc/
$ wget https://raw.githubusercontent.com/localgovdrupal/localgov_directories/fix/2.x/100-repeated-back-to-results-link/js/localgov_directories_entry_search.js
$ mv localgov_directories_entry_search.js localgov_directories_entry_search.es6.js
$ popd
$ yarn install
$ yarn build:js
$ tail misc/localgov_directories_entry_search.js
```

**Comment by Adnan-cds** [comment]
> Am I allowed to use '.?' 

Sorry Ekes, just seeing your comment above regarding the optional chaining operator.  For whatever reason, I didn't get any notification email about that comment :(  But I really don't have an answer either :)

**Comment by ekes** [comment]
I'd just do somthing like `once().forEach(function ($e) { $e.insertBefore() })` without the .? I think. It's basically IE11 isn't it? And it's an enhancement. So I thought I'd go for it and check ;-)

**Comment by Adnan-cds** [comment]
> I'd just do somthing like once().forEach(function ($e) { $e.insertBefore() })

+1

**Comment by Adnan-cds** [comment]
Thanks Ekes.

**Pull request merged**
