### PR TITLE
Remove error if the block does not exist to suppress error on install.

### LINKED ISSUE #194: Remove `Block %block-id is missing.  Cannot update its visibility settings.` error message as it serves no purpose
When enabling directories in Microsites two separate error alerts are thrown:

```
 [error]  Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 482 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 482 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
```

Looks related to #43 and #157

```
[error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings. 
```

Looks to be due to https://github.com/localgovdrupal/localgov_directories/blob/0d2d1e51458479c06339a47719d69c283c619649/localgov_directories.module#L229

### PR DESCRIPTION
**Pull request by finnlewis**
Fixes #194 and #249 which is a problem for LocalGov Microsites fresh install.

### CODE REVIEW

**Comment by finnlewis** [comment]
I can confirm that this suppresses the error mentioned in #249.

**Comment by finnlewis** [comment]
@Adnan-cds you OK with this?

**Review by Adnan-cds — APPROVED** [review]
Hi Finn,
Yes, I am okay with this change.

**Review by stephen-cox — APPROVED** [review]
Looks good to me :+1:

**Comment by finnlewis** [comment]
Thanks @Adnan-cds  and @stephen-cox  - merged! I'll tag a release to suppress the error on fresh installs of microsites.

**Pull request merged**
