### PR TITLE
Changed field formatter default for Enquiries email from text to email issue #340

### PR DESCRIPTION
**Pull request by bisd**
This is to complete PR https://github.com/localgovdrupal/localgov_base/pull/523.
It relates to issue https://github.com/localgovdrupal/localgov_directories/issues/340

### CODE REVIEW

**Comment by ekes** [comment]
Looks good, but I think we really only want the change to line 74. I suspect the next person coming along will put back `{  }` for `{}` as that's how they export at the moment... or has this changed?

**Comment by bisd** [comment]
Thanks @ekes. VSCode is deleting the spaces within the braces on saving so I opened it in Sublime Text and reverted the spaces. The PR is still failing tests I am not sure why.

**Review by ekes — APPROVED** [review]
Failing tests are unrelated to this change.

Works now for setting the email to a link.

**Comment by ekes** [comment]
@bisd nice one thanks.

**Pull request merged**
