### PR TITLE
Upgrade facets to 2.0

### LINKED ISSUE #175: Facets 1.x is now unsupported
Facets has released 2.0 https://www.drupal.org/project/facets

And 1.x is now marked as unsupported.
Screenshot 2021-12-15 at 3 01 06 pm

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #175

### CODE REVIEW

**Comment by andybroomfield** [comment]
Open refferal also needs the update
https://github.com/localgovdrupal/localgov_openreferral/pull/23

**Comment by andybroomfield** [comment]
Local testing on a directory with mutliple facets seems to work ok.

**Comment by ekes** [comment]
OpenReferral first, but with the update almost certainly just being the 8.x and PHP7.1 support dropped, if the multiple facets are good manually tested, and the tests pass once OR is there we'll be go to go.

**Comment by ekes** [comment]
Dependencies now work : https://github.com/localgovdrupal/localgov/pull/409

**Review by finnlewis — APPROVED** [review]
Discussing on 'merge Monday' call, good to merge and will release alongside localgovdrupal/localgov_geo#49

**Pull request merged**
