### PR TITLE
Add config for a new directory page type

### PR DESCRIPTION
**Pull request by msayoung**
Background: https://github.com/localgovdrupal/localgov_microsites/issues/149

### CODE REVIEW

**Comment by finnlewis** [comment]
Discussing in Merge Monday meeting.

@ekes pointed out we need to add some tests to confirm that the page works, following suit from the other content types in directories.

@andybroomfield in composr.json we need to add a composer 'suggests' line for localgov_paragraphs and anything else that we might want people to require (like this https://github.com/localgovdrupal/localgov_microsites_group/blob/1.x/composer.json#L18)

Also need to add 'require-dev' to list the same dependencies, like https://github.com/localgovdrupal/localgov_microsites_group/blob/1.x/composer.json#L15

Coding standards also need fixing.

**Comment by finnlewis** [comment]
@msayoung merged 2.x back into this branch, tests now passing :)

**Comment by finnlewis** [comment]
testing this with: 

```
lando composer require "localgovdrupal/localgov_paragraphs:2.x-dev as 2.1.1" -W
lando composer require "localgovdrupal/localgov_directories:dev-feature/2.x/149-new-directory-page as 2.x-dev" -W
lando composer require "localgovdrupal/localgov_microsites_group:dev-feature/add-permissions-promo-page as 1.x-dev" -W
lando phpunit web/modules/contrib/localgov_directories/
```
And i get a couple of failing tests: 

```
Summary of non-successful tests:

Facet Sync (Drupal\Tests\localgov_directories_or\Kernel\FacetSync)
 ☢ Syncronise facet mappings
 ☢ Syncronise facet mappings

Services Integration (Drupal\Tests\localgov_directories\Functional\ServicesIntegration)
 ✘ Services integration
   ┐
   ├ Undefined array key "localgov_services_landing"
   │
   ╵ /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:125
   ╵ /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
   ╵ /app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:474
   ╵ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:559
   ╵ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:378
   ╵ /app/web/modules/contrib/localgov_directories/tests/src/Functional/ServicesIntegrationTest.php:65
   ╵ /app/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
   ┴

ERRORS!
Tests: 20, Assertions: 319, Errors: 2, Risky: 1.
```

**Comment by finnlewis** [comment]
Actually - sorry - just realised that I was running all tests for localgov_directories against the localgov_microsites codebase, which does not include localgov_services. 

A fresh update of localgov propoer, then:

```
lando composer require "localgovdrupal/localgov_paragraphs:2.x-dev as 2.1.1" -W
lando composer require "localgovdrupal/localgov_directories:dev-feature/2.x/149-new-directory-page as 2.x-dev" -W
lando phpunit web/modules/contrib/localgov_directories/
```

All tests pass for me locally.

**Comment by finnlewis** [comment]
So I think maybe we need the release of localgov_paragraphs: 

https://github.com/localgovdrupal/localgov_paragraphs/pull/65/files#diff-6a0b7d5aa21cde05cb01f4a19d626d527bec449a8497f2b0da9a714b2d4b3f36R8

**Comment by msayoung** [comment]
thanks @finnlewis !

**Comment by finnlewis** [comment]
Just testing against the main localgov install.

**Review by finnlewis — APPROVED** [review]
Works a treat on default localgov install profile too. Test pass. Nice one @msayoung - sorry it took me a while to test!

**Comment by ekes** [comment]
Proposed some documentation / explanation of the content types #208

**Pull request merged**
