### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by AWearring**
Removed patch for `PHP 8.2 compatibility for the 2.0.x branch: https://www.drupal.org/project/facets/issues/3336646` as this has been fixed in 2.0.7 of Drupal Facets Module: https://www.drupal.org/project/facets/releases/2.0.7

### CODE REVIEW

**Review by millnut — CHANGES_REQUESTED** [review]
Hi @AWearring it doesn't look like the formatting for this is correct

**Comment by AWearring** [comment]
@millnut Should be sorted now - a case of "more haste and less speed"

**Comment by ekes** [comment]
Should we be sure that it updates then? So contstraining facets to ^2.0.7?

**Comment by millnut** [comment]
> Should we be sure that it updates then? So contstraining facets to ^2.0.7?

Yep 2.0.7 is marked as recommended so I think we can increase the constraint to `^2.0.7` in composer.json

**Comment by AWearring** [comment]
> > Should we be sure that it updates then? So contstraining facets to ^2.0.7?
> 
> Yep 2.0.7 is marked as recommended so I think we can increase the constraint to `^2.0.7` in composer.json

Done

**Review by finnlewis — APPROVED** [review]
Looks good to me, thanks @AWearring !

**Pull request merged**
