### PR TITLE
Facet block configurations. Update conditions, ensure installed.

### PR DESCRIPTION
**Pull request by ekes**
- Update the facet visibility,
 - Load the optional block config when facet config updated.

Fixes at least part of #355

### CODE REVIEW

**Comment by ekes** [comment]
I'm sure I'd pulled :-/. Lets check these conflicts.

**Comment by ekes** [comment]
There we go.

**Comment by finnlewis** [comment]
I think all the changes here are included in https://github.com/localgovdrupal/localgov_directories/pull/359/files, so do we close this pull request in favour of 359?

**Comment by finnlewis** [comment]
Shall we close this one then @ekes ?

**Comment by finnlewis** [comment]
Closing a duplicate.

**Pull request closed without merging**
