### PR TITLE
updated labels and added update hook

### LINKED ISSUE #72: Back end: Rename "Directory" tab "Channels and facets"
On "directory venue" and "directory page" content types, the "Directory" channel does not describe the options beneath

We should call this tab "Channels and facets" as they're the options a content designer can select from

See screenshots for an example

### PR DESCRIPTION
**Pull request by mattrfletcher**
Fix for #72 - Rename Directory tab channels and facets

### CODE REVIEW

**Comment by mattrfletcher** [comment]
@finnlewis @stephen-cox @ekes @Adnan-cds 

As mentioned at the meeting this is a pull request that needs to be approved.

**Comment by finnlewis** [comment]
Thanks @mattrfletcher  - just triggered the tests to run, and I'll try to test the branch too.

**Comment by stephen-cox** [comment]
@mattrfletcher This looks good, but there have been some recent changes to branches. Can you pull the latest changes from the 2.x branch, merge them into your branch and push? This will trigger the tests again. If you add me as a reviewer to this PR once you've done this I'll take another look.

**Comment by mattrfletcher** [comment]
@stephen-cox I've pulled the 2.x branch merged it and done another push.

**Comment by mattrfletcher** [comment]
@finnlewis @stephen-cox As all checks have passed is there else I need to do before this gets merged. Are you waiting for a certain time or something else to happen before this gets merged.

**Comment by stephen-cox** [comment]
Thanks @mattrfletcher. Looks good. Merging

**Pull request merged**
