### PR TITLE
Update the form display for the directory promo page

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
Before

image

After: 

image

- exposed the summary field (as per other Directory items)
- changed the banner field display, to not default to select seconday banner paragraph as it caused confusion in testing
- put the banner and standfirst fields in a fieldset with help text
- renamed "Content" field to "Layouts and rich content" - updated help text

**Comment by msayoung** [comment]
@finnlewis @willguv 
Thoughts on the above changes? If you think they are good we can roll them out to Page, Events and News where we have the same. 

Particular changes:

- changed the banner field display, to not default to select seconday banner paragraph as it caused confusion in testing
- put the banner and standfirst fields in a fieldset with help text
- renamed "Content" field to "Layouts and rich content" - updated help text

Does it help? Is it clearer?

**Comment by finnlewis** [comment]
Thanks @msayoung - all those changes look like good ones to me!

**Review by finnlewis — APPROVED** [review]
Tested locally, and works as advertised. The form is certainly tidier and I expect easier to use. 

Tests all pass and this is only for new installs. 

Thanks @msayoung !

**Pull request merged**
