### PR TITLE
Fix code deprecation warnings by replacing render() with the renderer…

### LINKED ISSUE #172: Call to deprecated function drupal_get_path()
From https://github.com/localgovdrupal/localgov_geo/issues/45

We have a number of code deprecation warnings.

```
------ -------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/localgov_directories.module    
 ------ -------------------------------------------------------------------- 
  339    Call to deprecated function drupal_get_path():                      
         in drupal:9.3.0 and is removed from drupal:10.0.0. Use              
           \Drupal\Core\Extension\ExtensionPathResolver::getPath() instead.  
 ------ -------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------------ 
  Line   modules/contrib/localgov_directories/modules/localgov_directories_location/localgov_directories_location.install  
 ------ ------------------------------------------------------------------------------------------------------------------ 
  16     Call to deprecated function drupal_get_path():                                                                    
         in drupal:9.3.0 and is removed from drupal:10.0.0. Use                                                            
           \Drupal\Core\Extension\ExtensionPathResolver::getPath() instead.                                                
  34     Call to deprecated function drupal_get_path():                                                                    
         in drupal:9.3.0 and is removed from drupal:10.0.0. Use                                                            
           \Drupal\Core\Extension\ExtensionPathResolver::getPath() instead.                                                
 ------ ------------------------------------------------------------------------------------------------------------------ 

 ------ --------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/src/Form/LocalgovDirectoriesFacetsForm.php  
 ------ --------------------------------------------------------------------------------- 
  23     Call to deprecated function render():                                            
         in drupal:9.3.0 and is removed from drupal:10.0.0. Use                           
           \Drupal\Core\Render\RendererInterface::render() instead.                       
 ------ ---------------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by finnlewis**
… service.

### CODE REVIEW

**Comment by finnlewis** [comment]
@ekes can you rework this one with the dependency injection?

**Comment by ekes** [comment]
> @ekes can you rework this one with the dependency injection?

This is what I did to inject on geo
https://github.com/localgovdrupal/localgov_geo/pull/46/files#diff-1b6d84fd5f648ca317b091fc5f1176f333665daf9ae4649216ab837a966fff16
(not yet tested).

**Comment by finnlewis** [comment]
OK, thanks @ekes, I will try to do the same here.

**Comment by finnlewis** [comment]
This is now also good to go. The failures are with deprecated code from other modules.

**Pull request merged**
