### PR TITLE
adds embed views paragraph type to promo content type

### LINKED ISSUE #221: Add embed views to promo content type

### PR DESCRIPTION
**Pull request by markconroy**
Closes #221

### CODE REVIEW

**Review by msayoung — CHANGES_REQUESTED** [review]
I think something's missing:

```
Configuration objects provided by <em class="placeholder">localgov_directories_promo_page</em> have unmet dependencies: <em class="placeholder">field.field.node.localgov_directory_promo_page.localgov_paragraph_content (paragraphs.paragraphs_type.local  
  gov_embed_views)</em>               
```                                                       

Edit: I found the other branches - testing again

**Comment by markconroy** [comment]
It should work for you now. I was missing a dependency

**Comment by msayoung** [comment]
Unfortunately I'm now getting 

```
In PreExistingConfigException.php line 65:
                                                                                                                                                                                       
  Configuration objects (field.field.node.localgov_directory_promo_page.localgov_paragraph_content) provided by localgov_microsites_directories already exist in active configuration 
```

**Comment by msayoung** [comment]
All good now. Had https://github.com/localgovdrupal/localgov_microsites_group/pull/208 checked out locally, but I see that's moved here.

**Review by msayoung — APPROVED** [review]

**Pull request merged**
