### PR TITLE
2.4.0 release

### PR DESCRIPTION
**Pull request by ekes**

### CODE REVIEW

**Comment by ekes** [comment]
MM this should include a update hook to add in the path alias if installed and none yet set.

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov_directories/pull/255 for the update hook.

**Comment by finnlewis** [comment]
waiting for https://github.com/localgovdrupal/localgov_directories/pull/255

**Comment by finnlewis** [comment]
This release now includes potentail API changes 

https://github.com/localgovdrupal/localgov_directories/pull/253/files#diff-118751fdb44d76d8d3f435d224b55591883bf325ae2fd136581f092d0f28534aL127

So @ekes suggests that strictly speaking, we should bump the minor version number to 2.4.0

We can review on Monday but any comments welcome before @andybroomfield @Adnan-cds @stephen-cox

**Comment by andybroomfield** [comment]
2.4.0 would be safer and technically correct if there is an api break risk.
I would be tempted to also mark them as internal if thats intended, though that can wait till 2.4.1 I suppose.

**Review by finnlewis — APPROVED** [review]
Looks good, we'll make release notes that explain.

**Pull request merged**
