### PR TITLE
Standardise field order on node edit page

### LINKED ISSUE #283: Standardise field order
Spun out of https://github.com/localgovdrupal/localgov/issues/487

For directories:

- the parent field needs to be first
- the field should be labelled "parent page"
- it's type should be a lookup not a drop down menu

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #283

### CODE REVIEW

**Comment by stephen-cox** [comment]
With these changes the directory channel edit page now looks like:

image

**Comment by willguv** [comment]
This is great, thanks @stephen-cox. Would I ordinarily merge this pull request?

**Review by finnlewis — APPROVED** [review]
Thanks @stephen-cox

**Comment by finnlewis** [comment]
> This is great, thanks @stephen-cox. Would I ordinarily merge this pull request?

@willguv our standard approach is for the developer making the pull request to merge once someone else has approved the pull request. Sometimes pull requests come from someone who does not have permissions to merge in our repository, in which case we review and merge usually at Merge Monday meetings.

**Pull request merged**
