### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by andybroomfield** [comment]
I'm seeing this error when trying to enable the new directories promo page type
> ResponseText: DivisionByZeroError: Division by zero in Drupal\search_api\Task\TaskManager->processBatch() (line 370 of /app/web/modules/contrib/search_api/src/Task/TaskManager.php).

This might be more releated to search so I'm doing some digging before setting up a new issue.

**Comment by ekes** [comment]
> I'm seeing this error when trying to enable the new directories promo page type
> 
> > ResponseText: DivisionByZeroError: Division by zero in Drupal\search_api\Task\TaskManager->processBatch() (line 370 of /app/web/modules/contrib/search_api/src/Task/TaskManager.php).
> 
> This might be more releated to search so I'm doing some digging before setting up a new issue.

I've just installed and enabled via the commandline and the UI and don't get the message.

@andybroomfield  Could it be that you have one of the search_api branches checked out?

**Comment by finnlewis** [comment]
Just tested this on a fresh install of the localgov_microsites install profile and on a fresh install of the localgov install profile.

All works fine as far as I can tell.

**Comment by finnlewis** [comment]
OK to release this @ekes @andybroomfield ?

**Comment by andybroomfield** [comment]
@ekes Ok had the search branch also checked out, this seems to work ok now.

**Review by andybroomfield — APPROVED** [review]

**Pull request merged**
