### PR TITLE
Directory facets label

### PR DESCRIPTION
**Pull request by Adnan-cds**
Fix for minor typo.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
I had to add the **shivammathur/setup-php@v2** action to the Github actions test workflow file to get past the chaos caused by composer v2.  Happy to drop it if you want to.

**Comment by stephen-cox** [comment]
Happy with the typo fix, but not sure about committing the update to the Github CI stuff until we have decided on a definite solution to the problem. I have added some comments on the issue here about the CI issues: https://github.com/localgovdrupal/localgov/issues/152#issuecomment-720356634

**Comment by Adnan-cds** [comment]
Hi Steve,
I have just tried to replace the **shivammathur/setup-php@v2** action with [changes similar to the composer pinning task](https://github.com/localgovdrupal/drupal-container/pull/10/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R20).  Unfortunately the "actions/checkout@v2" action is having [file permission issues](https://github.com/localgovdrupal/localgov_directories/runs/1341576198?check_suite_focus=true#step:5:19).  I am wondering what I have missed.  Could you please take a look when you have some time.

FAO @stephen-cox

**Comment by Adnan-cds** [comment]
This one has been superseded by #48

**Pull request closed without merging**
