### PR TITLE
Add 'Add directory facet type' button to directory facets management page

### PR DESCRIPTION
**Pull request by stephen-cox**
For discussion see: https://github.com/localgovdrupal/localgov_directories/issues/276#issuecomment-1498916345

### CODE REVIEW

**Comment by finnlewis** [comment]
Not ready just yet, need to check the UX and workflow of adding facet types and facets.

**Comment by willguv** [comment]
@stephen-cox could I see this working somewhere please? Many thanks

**Comment by stephen-cox** [comment]
> @stephen-cox could I see this working somewhere please? Many thanks

@willguv I've deployed it here: https://test.localgovdrupal.org/admin/content/directories/facets

**Comment by willguv** [comment]
Thanks @stephen-cox agree it's not perfect, but it's an improvement on what we have now. Users can add facet types from /admin/content/directories/facets which they were unable to do before

Would it be a lot of work to direct users adding a facet type from https://test.localgovdrupal.org/admin/content/directories/facets back to that page once added? If they then want to add a facet to that type, there's a clear route

Let's talk separately about an overhaul

**Comment by stephen-cox** [comment]
We would need to implement some sort of hook to add the redirect, it shouldn't be too much work, but would need to investigate to determine the best way to implement this.

One issue that the redirect would apply to anyone who added a directory facet, which is not necessarily the best behavior; someone might want to add a bunch of facet types before then adding the facets. We could check the referrer header and only redirect when the user came from the facet management page, but this feels a bit hacky.

**Comment by willguv** [comment]
@stephen-cox could you describe how to rework this in the taxonomy style? Am trying to picture it - thanks

**Comment by finnlewis** [comment]
@stephen-cox I've just added a new action link with a destination to return users to the facet content page after adding a facet from there. 

So now, if we are at admin/content/directories/facets and click on "Add directory facet type" we can add a facet type and get returned to admin/content/directories/facets

If we are admin/structure/localgov_directories_facets_types and click on "Add directory facet type" we can add a facet type and get returned to admin/structure/localgov_directories_facets_types

Does that work?

**Comment by stephen-cox** [comment]
> @stephen-cox could you describe how to rework this in the taxonomy style? Am trying to picture it - thanks

@willguv What I had i mind is what's been implemented for Microsites

The the main directory facets page lists the types:

image

Clicking on a type takes you to the facets for that type

image

**Comment by willguv** [comment]
@stephen-cox that's much clearer - how long to implement please?

Will there be any issues for existing installs?

**Comment by stephen-cox** [comment]
> @stephen-cox I've just added a new action link with a destination to return users to the facet content page after adding a facet from there.
> Does that work?

Nice one @finnlewis Does the job :+1:

**Review by ekes — APPROVED** [review]

**Pull request merged**
