### PR TITLE
Also add facet configuration on updating the index (enabling)

### PR DESCRIPTION
**Pull request by ekes**
Second part of #355

### CODE REVIEW

**Comment by ekes** [comment]
Normally the facet configuration is added when the facets field is added to the index. This doesn't happen if the index isn't enabled. Seems be the case for microsites where it is installed in one go, could be anywhere else though. This hook should check for the field and facet configuration also when the search index is enabled.

**Comment by finnlewis** [comment]
Nice on @ekes  - testing this now.

**Comment by finnlewis** [comment]
Yup, this works better now on a fresh install of LocalGov Microsites. 

Tests pass too... happy to get this merged.

Do we also want to cherry-pick / back-port to 2.x?

**Review by finnlewis — APPROVED** [review]
:+1:

**Pull request merged**
